apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react-service
spec:
  selector:
    app: react-application
  type: NodePort
  ports:
    - port: 80       # The port your service listens on
      targetPort: 80 # The port the container listens on
      nodePort: 30080  # The port exposed on the node
      protocol: TCP
